name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
    
    - uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install
    
    - uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: build
    
    - uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: test

